export const INDIAN_STATES = [
  { label: 'Andhra Pradesh', value: 'AP' }, 
  { label: 'Arunachal Pradesh', value: 'AR' },
  { label: 'Assam', value: 'AS' }, 
  { label: 'Bihar', value: 'BR' },
  { label: 'Chhattisgarh', value: 'CG' }, 
  { label: 'Goa', value: 'GA' },
  { label: 'Gujarat', value: 'GJ' }, 
  { label: 'Haryana', value: 'HR' },
  { label: 'Himachal Pradesh', value: 'HP' }, 
  { label: 'Jharkhand', value: 'JH' },
  { label: 'Karnataka', value: 'KA' }, 
  { label: 'Kerala', value: 'KL' },
  { label: 'Madhya Pradesh', value: 'MP' }, 
  { label: 'Maharashtra', value: 'MH' },
  { label: 'Manipur', value: 'MN' }, 
  { label: 'Meghalaya', value: 'ML' },
  { label: 'Mizoram', value: 'MZ' }, 
  { label: 'Nagaland', value: 'NL' },
  { label: 'Odisha', value: 'OR' }, 
  { label: 'Punjab', value: 'PB' },
  { label: 'Rajasthan', value: 'RJ' }, 
  { label: 'Sikkim', value: 'SK' },
  { label: 'Tamil Nadu', value: 'TN' }, 
  { label: 'Telangana', value: 'TG' },
  { label: 'Tripura', value: 'TR' }, 
  { label: 'Uttar Pradesh', value: 'UP' },
  { label: 'Uttarakhand', value: 'UK' }, 
  { label: 'West Bengal', value: 'WB' },
  { label: 'Andaman & Nicobar', value: 'AN' }, 
  { label: 'Chandigarh', value: 'CH' },
  { label: 'Dadra & Nagar Haveli', value: 'DN' }, 
  { label: 'Daman & Diu', value: 'DD' },
  { label: 'Delhi', value: 'DL' }, 
  { label: 'Jammu & Kashmir', value: 'JK' },
  { label: 'Ladakh', value: 'LA' }, 
  { label: 'Lakshadweep', value: 'LD' },
  { label: 'Puducherry', value: 'PY' }
];

export const CITIES_BY_STATE: Record<string, { label: string, value: string }[]> = {
  AP: [
    { label: 'Visakhapatnam', value: 'visakhapatnam' }, 
    { label: 'Vijayawada', value: 'vijayawada' }, 
    { label: 'Guntur', value: 'guntur' }, 
    { label: 'Nellore', value: 'nellore' },
    { label: 'Kurnool', value: 'kurnool' },
    { label: 'Tirupati', value: 'tirupati' },
    { label: 'Rajahmundry', value: 'rajahmundry' },
    { label: 'Kakinada', value: 'kakinada' },
    { label: 'Kadapa', value: 'kadapa' },
    { label: 'Anantapur', value: 'anantapur' },
    { label: 'Vizianagaram', value: 'vizianagaram' },
    { label: 'Eluru', value: 'eluru' },
    { label: 'Ongole', value: 'ongole' },
    { label: 'Nandyal', value: 'nandyal' },
    { label: 'Machilipatnam', value: 'machilipatnam' },
    { label: 'Adoni', value: 'adoni' },
    { label: 'Tenali', value: 'tenali' },
    { label: 'Chittoor', value: 'chittoor' },
    { label: 'Hindupur', value: 'hindupur' },
    { label: 'Proddatur', value: 'proddatur' }
  ],
  AR: [
    { label: 'Itanagar', value: 'itanagar' }, 
    { label: 'Tawang', value: 'tawang' },
    { label: 'Pasighat', value: 'pasighat' },
    { label: 'Ziro', value: 'ziro' },
    { label: 'Tezu', value: 'tezu' },
    { label: 'Namsai', value: 'namsai' },
    { label: 'Bomdila', value: 'bomdila' },
    { label: 'Khonsa', value: 'khonsa' },
    { label: 'Aalo (Along)', value: 'aalo' },
    { label: 'Roing', value: 'roing' }
  ],
  AS: [
    { label: 'Guwahati', value: 'guwahati' }, 
    { label: 'Dibrugarh', value: 'dibrugarh' }, 
    { label: 'Silchar', value: 'silchar' },
    { label: 'Jorhat', value: 'jorhat' },
    { label: 'Nagaon', value: 'nagaon' },
    { label: 'Tinsukia', value: 'tinsukia' },
    { label: 'Tezpur', value: 'tezpur' },
    { label: 'Bongaigaon', value: 'bongaigaon' },
    { label: 'Sivasagar', value: 'sivasagar' },
    { label: 'Karimganj', value: 'karimganj' },
    { label: 'Dhubri', value: 'dhubri' },
    { label: 'Diphu', value: 'diphu' },
    { label: 'North Lakhimpur', value: 'north_lakhimpur' },
    { label: 'Goalpara', value: 'goalpara' },
    { label: 'Barpeta', value: 'barpeta' }
  ],
  BR: [
    { label: 'Patna', value: 'patna' }, 
    { label: 'Gaya', value: 'gaya' }, 
    { label: 'Bhagalpur', value: 'bhagalpur' },
    { label: 'Muzaffarpur', value: 'muzaffarpur' },
    { label: 'Purnia', value: 'purnia' },
    { label: 'Darbhanga', value: 'darbhanga' },
    { label: 'Bihar Sharif', value: 'bihar_sharif' },
    { label: 'Arrah', value: 'arrah' },
    { label: 'Begusarai', value: 'begusarai' },
    { label: 'Katihar', value: 'katihar' },
    { label: 'Munger', value: 'munger' },
    { label: 'Chhapra', value: 'chhapra' },
    { label: 'Bettiah', value: 'bettiah' },
    { label: 'Saharsa', value: 'saharsa' },
    { label: 'Sasaram', value: 'sasaram' },
    { label: 'Hajipur', value: 'hajipur' },
    { label: 'Dehri', value: 'dehri' },
    { label: 'Siwan', value: 'siwan' },
    { label: 'Motihari', value: 'motihari' },
    { label: 'Nawada', value: 'nawada' }
  ],
  CG: [
    { label: 'Raipur', value: 'raipur' }, 
    { label: 'Bhilai', value: 'bhilai' }, 
    { label: 'Bilaspur', value: 'bilaspur' },
    { label: 'Korba', value: 'korba' },
    { label: 'Durg', value: 'durg' },
    { label: 'Rajnandgaon', value: 'rajnandgaon' },
    { label: 'Jagdalpur', value: 'jagdalpur' },
    { label: 'Ambikapur', value: 'ambikapur' },
    { label: 'Dhamtari', value: 'dhamtari' },
    { label: 'Mahasamund', value: 'mahasamund' },
    { label: 'Raigarh', value: 'raigarh' },
    { label: 'Champa', value: 'champa' },
    { label: 'Bhatapara', value: 'bhatapara' }
  ],
  GA: [
    { label: 'Panaji', value: 'panaji' }, 
    { label: 'Margao', value: 'margao' }, 
    { label: 'Vasco da Gama', value: 'vasco' },
    { label: 'Mapusa', value: 'mapusa' },
    { label: 'Ponda', value: 'ponda' },
    { label: 'Bicholim', value: 'bicholim' },
    { label: 'Curchorem', value: 'curchorem' },
    { label: 'Mormugao', value: 'mormugao' }
  ],
  GJ: [
    { label: 'Ahmedabad', value: 'ahmedabad' }, 
    { label: 'Surat', value: 'surat' }, 
    { label: 'Vadodara', value: 'vadodara' }, 
    { label: 'Rajkot', value: 'rajkot' },
    { label: 'Bhavnagar', value: 'bhavnagar' },
    { label: 'Jamnagar', value: 'jamnagar' },
    { label: 'Junagadh', value: 'junagadh' },
    { label: 'Gandhinagar', value: 'gandhinagar' },
    { label: 'Nadiad', value: 'nadiad' },
    { label: 'Morbi', value: 'morbi' },
    { label: 'Anand', value: 'anand' },
    { label: 'Bharuch', value: 'bharuch' },
    { label: 'Vapi', value: 'vapi' },
    { label: 'Navsari', value: 'navsari' },
    { label: 'Veraval', value: 'veraval' },
    { label: 'Porbandar', value: 'porbandar' },
    { label: 'Godhra', value: 'godhra' },
    { label: 'Bhuj', value: 'bhuj' },
    { label: 'Mehsana', value: 'mehsana' },
    { label: 'Valsad', value: 'valsad' }
  ],
  HR: [
    { label: 'Gurugram', value: 'gurugram' }, 
    { label: 'Faridabad', value: 'faridabad' }, 
    { label: 'Panipat', value: 'panipat' },
    { label: 'Ambala', value: 'ambala' },
    { label: 'Yamunanagar', value: 'yamunanagar' },
    { label: 'Rohtak', value: 'rohtak' },
    { label: 'Hisar', value: 'hisar' },
    { label: 'Karnal', value: 'karnal' },
    { label: 'Sonipat', value: 'sonipat' },
    { label: 'Panchkula', value: 'panchkula' },
    { label: 'Sirsa', value: 'sirsa' },
    { label: 'Bhiwani', value: 'bhiwani' },
    { label: 'Bahadurgarh', value: 'bahadurgarh' },
    { label: 'Jind', value: 'jind' },
    { label: 'Thanesar', value: 'thanesar' },
    { label: 'Palwal', value: 'palwal' },
    { label: 'Rewari', value: 'rewari' }
  ],
  HP: [
    { label: 'Shimla', value: 'shimla' }, 
    { label: 'Dharamshala', value: 'dharamshala' }, 
    { label: 'Solan', value: 'solan' },
    { label: 'Mandi', value: 'mandi' },
    { label: 'Baddi', value: 'baddi' },
    { label: 'Una', value: 'una' },
    { label: 'Kullu', value: 'kullu' },
    { label: 'Hamirpur', value: 'hamirpur' },
    { label: 'Chamba', value: 'chamba' },
    { label: 'Paonta Sahib', value: 'paonta_sahib' },
    { label: 'Bilaspur', value: 'bilaspur_hp' },
    { label: 'Nahan', value: 'nahan' }
  ],
  JH: [
    { label: 'Ranchi', value: 'ranchi' }, 
    { label: 'Jamshedpur', value: 'jamshedpur' }, 
    { label: 'Dhanbad', value: 'dhanbad' },
    { label: 'Bokaro Steel City', value: 'bokaro' },
    { label: 'Deoghar', value: 'deoghar' },
    { label: 'Hazaribagh', value: 'hazaribagh' },
    { label: 'Giridih', value: 'giridih' },
    { label: 'Ramgarh', value: 'ramgarh' },
    { label: 'Phusro', value: 'phusro' },
    { label: 'Medininagar (Daltonganj)', value: 'medininagar' },
    { label: 'Chas', value: 'chas' },
    { label: 'Sahibganj', value: 'sahibganj' },
    { label: 'Dumka', value: 'dumka' },
    { label: 'Chaibasa', value: 'chaibasa' }
  ],
  KA: [
    { label: 'Bengaluru', value: 'bengaluru' }, 
    { label: 'Mysuru', value: 'mysuru' }, 
    { label: 'Hubballi', value: 'hubballi' }, 
    { label: 'Mangaluru', value: 'mangaluru' },
    { label: 'Belagavi', value: 'belagavi' },
    { label: 'Kalaburagi (Gulbarga)', value: 'kalaburagi' },
    { label: 'Davangere', value: 'davangere' },
    { label: 'Ballari (Bellary)', value: 'ballari' },
    { label: 'Vijayapura (Bijapur)', value: 'vijayapura' },
    { label: 'Shivamogga (Shimoga)', value: 'shivamogga' },
    { label: 'Tumakuru (Tumkur)', value: 'tumakuru' },
    { label: 'Raichur', value: 'raichur' },
    { label: 'Bidar', value: 'bidar' },
    { label: 'Hosapete (Hospet)', value: 'hosapete' },
    { label: 'Gadag', value: 'gadag' },
    { label: 'Udupi', value: 'udupi' },
    { label: 'Hassan', value: 'hassan' },
    { label: 'Chitradurga', value: 'chitradurga' },
    { label: 'Kolar', value: 'kolar' },
    { label: 'Mandya', value: 'mandya' }
  ],
  KL: [
    { label: 'Thiruvananthapuram', value: 'trivandrum' }, 
    { label: 'Kochi', value: 'kochi' }, 
    { label: 'Kozhikode', value: 'kozikode' },
    { label: 'Kollam', value: 'kollam' },
    { label: 'Thrissur', value: 'thrissur' },
    { label: 'Alappuzha', value: 'alappuzha' },
    { label: 'Palakkad', value: 'palakkad' },
    { label: 'Kannur', value: 'kannur' },
    { label: 'Kottayam', value: 'kottayam' },
    { label: 'Malappuram', value: 'malappuram' },
    { label: 'Manjeri', value: 'manjeri' },
    { label: 'Thalassery', value: 'thalassery' },
    { label: 'Ponnani', value: 'ponnani' },
    { label: 'Vatakara', value: 'vatakara' },
    { label: 'Kanhangad', value: 'kanhangad' }
  ],
  MP: [
    { label: 'Indore', value: 'indore' }, 
    { label: 'Bhopal', value: 'bhopal' }, 
    { label: 'Jabalpur', value: 'jabalpur' }, 
    { label: 'Gwalior', value: 'gwalior' },
    { label: 'Ujjain', value: 'ujjain' },
    { label: 'Sagar', value: 'sagar' },
    { label: 'Dewas', value: 'dewas' },
    { label: 'Satna', value: 'satna' },
    { label: 'Ratlam', value: 'ratlam' },
    { label: 'Rewa', value: 'rewa' },
    { label: 'Murwara (Katni)', value: 'katni' },
    { label: 'Singrauli', value: 'singrauli' },
    { label: 'Burhanpur', value: 'burhanpur' },
    { label: 'Khandwa', value: 'khandwa' },
    { label: 'Bhind', value: 'bhind' },
    { label: 'Chhindwara', value: 'chhindwara' },
    { label: 'Guna', value: 'guna' },
    { label: 'Shivpuri', value: 'shivpuri' },
    { label: 'Vidisha', value: 'vidisha' },
    { label: 'Damoh', value: 'damoh' }
  ],
  MH: [
    { label: 'Mumbai', value: 'mumbai' }, 
    { label: 'Pune', value: 'pune' }, 
    { label: 'Nagpur', value: 'nagpur' }, 
    { label: 'Nashik', value: 'nashik' },
    { label: 'Thane', value: 'thane' },
    { label: 'Chhatrapati Sambhajinagar (Aurangabad)', value: 'aurangabad' },
    { label: 'Solapur', value: 'solapur' },
    { label: 'Amravati', value: 'amravati' },
    { label: 'Navi Mumbai', value: 'navi_mumbai' },
    { label: 'Kolhapur', value: 'kolhapur' },
    { label: 'Akola', value: 'akola' },
    { label: 'Jalgaon', value: 'jalgaon' },
    { label: 'Latur', value: 'latur' },
    { label: 'Dhule', value: 'dhule' },
    { label: 'Ahmednagar', value: 'ahmednagar' },
    { label: 'Chandrapur', value: 'chandrapur' },
    { label: 'Nanded', value: 'nanded' },
    { label: 'Sangli', value: 'sangli' },
    { label: 'Kalyan-Dombivli', value: 'kalyan_dombivli' },
    { label: 'Vasai-Virar', value: 'vasai_virar' },
    { label: 'Mira-Bhayandar', value: 'mira_bhayandar' },
    { label: 'Bhiwandi', value: 'bhiwandi' },
    { label: 'Amarnath', value: 'amarnath' },
    { label: 'Parbhani', value: 'parbhani' }
  ],
  MN: [
    { label: 'Imphal', value: 'imphal' },
    { label: 'Thoubal', value: 'thoubal' },
    { label: 'Churachandpur', value: 'churachandpur' },
    { label: 'Kakching', value: 'kakching' },
    { label: 'Ukhrul', value: 'ukhrul' },
    { label: 'Senapati', value: 'senapati' },
    { label: 'Jiribam', value: 'jiribam' }
  ],
  ML: [
    { label: 'Shillong', value: 'shillong' },
    { label: 'Tura', value: 'tura' },
    { label: 'Jowai', value: 'jowai' },
    { label: 'Nongpoh', value: 'nongpoh' },
    { label: 'Williamnagar', value: 'williamnagar' },
    { label: 'Baghmara', value: 'baghmara' },
    { label: 'Cherrapunji (Sohra)', value: 'cherrapunji' }
  ],
  MZ: [
    { label: 'Aizawl', value: 'aizawl' },
    { label: 'Lunglei', value: 'lunglei' },
    { label: 'Saiha', value: 'saiha' },
    { label: 'Champhai', value: 'champhai' },
    { label: 'Kolasib', value: 'kolasib' },
    { label: 'Serchhip', value: 'serchhip' },
    { label: 'Lawngtlai', value: 'lawngtlai' }
  ],
  NL: [
    { label: 'Kohima', value: 'kohima' }, 
    { label: 'Dimapur', value: 'dimapur' },
    { label: 'Mokokchung', value: 'mokokchung' },
    { label: 'Tuensang', value: 'tuensang' },
    { label: 'Wokha', value: 'wokha' },
    { label: 'Zunheboto', value: 'zunheboto' },
    { label: 'Mon', value: 'mon' },
    { label: 'Phek', value: 'phek' }
  ],
  OR: [
    { label: 'Bhubaneswar', value: 'bhubaneswar' }, 
    { label: 'Cuttack', value: 'cuttack' }, 
    { label: 'Rourkela', value: 'rourkela' },
    { label: 'Berhampur', value: 'berhampur' },
    { label: 'Sambalpur', value: 'sambalpur' },
    { label: 'Puri', value: 'puri' },
    { label: 'Balasore', value: 'balasore' },
    { label: 'Bhadrak', value: 'bhadrak' },
    { label: 'Baripada', value: 'baripada' },
    { label: 'Jharsuguda', value: 'jharsuguda' },
    { label: 'Balangir', value: 'balangir' },
    { label: 'Rayagada', value: 'rayagada' }
  ],
  PB: [
    { label: 'Ludhiana', value: 'ludhiana' }, 
    { label: 'Amritsar', value: 'amritsar' }, 
    { label: 'Jalandhar', value: 'jalandhar' },
    { label: 'Patiala', value: 'patiala' },
    { label: 'Bathinda', value: 'bathinda' },
    { label: 'SAS Nagar (Mohali)', value: 'mohali' },
    { label: 'Hoshiarpur', value: 'hoshiarpur' },
    { label: 'Pathankot', value: 'pathankot' },
    { label: 'Moga', value: 'moga' },
    { label: 'Abohar', value: 'abohar' },
    { label: 'Malerkotla', value: 'malerkotla' },
    { label: 'Khanna', value: 'khanna' },
    { label: 'Phagwara', value: 'phagwara' },
    { label: 'Muktsar', value: 'muktsar' },
    { label: 'Barnala', value: 'barnala' },
    { label: 'Firozpur', value: 'firozpur' }
  ],
  RJ: [
    { label: 'Jaipur', value: 'jaipur' }, 
    { label: 'Jodhpur', value: 'jodhpur' }, 
    { label: 'Udaipur', value: 'udaipur' }, 
    { label: 'Kota', value: 'kota' },
    { label: 'Bikaner', value: 'bikaner' },
    { label: 'Ajmer', value: 'ajmer' },
    { label: 'Bhilwara', value: 'bhilwara' },
    { label: 'Alwar', value: 'alwar' },
    { label: 'Sikar', value: 'sikar' },
    { label: 'Sri Ganganagar', value: 'ganganagar' },
    { label: 'Bharatpur', value: 'bharatpur' },
    { label: 'Pali', value: 'pali' },
    { label: 'Barmer', value: 'barmer' },
    { label: 'Chittorgarh', value: 'chittorgarh' },
    { label: 'Jhunjhunu', value: 'jhunjhunu' },
    { label: 'Churu', value: 'churu' },
    { label: 'Beawar', value: 'beawar' },
    { label: 'Nagaur', value: 'nagaur' }
  ],
  SK: [
    { label: 'Gangtok', value: 'gangtok' },
    { label: 'Namchi', value: 'namchi' },
    { label: 'Gyalshing', value: 'gyalshing' },
    { label: 'Mangan', value: 'mangan' },
    { label: 'Singtam', value: 'singtam' },
    { label: 'Rangpo', value: 'rangpo' },
    { label: 'Jorethang', value: 'jorethang' }
  ],
  TN: [
    { label: 'Chennai', value: 'chennai' }, 
    { label: 'Coimbatore', value: 'coimbatore' }, 
    { label: 'Madurai', value: 'madurai' },
    { label: 'Tiruchirappalli (Trichy)', value: 'trichy' },
    { label: 'Salem', value: 'salem' },
    { label: 'Tiruppur', value: 'tiruppur' },
    { label: 'Erode', value: 'erode' },
    { label: 'Vellore', value: 'vellore' },
    { label: 'Thoothukudi (Tuticorin)', value: 'thoothukudi' },
    { label: 'Tirunelveli', value: 'tirunelveli' },
    { label: 'Thanjavur', value: 'thanjavur' },
    { label: 'Dindigul', value: 'dindigul' },
    { label: 'Nagercoil', value: 'nagercoil' },
    { label: 'Kanchipuram', value: 'kanchipuram' },
    { label: 'Cuddalore', value: 'cuddalore' },
    { label: 'Kumbakonam', value: 'kumbakonam' },
    { label: 'Ambur', value: 'ambur' },
    { label: 'Karaikudi', value: 'karaikudi' },
    { label: 'Neyveli', value: 'neyveli' },
    { label: 'Hosur', value: 'hosur' }
  ],
  TG: [
    { label: 'Hyderabad', value: 'hyderabad' }, 
    { label: 'Warangal', value: 'warangal' },
    { label: 'Nizamabad', value: 'nizamabad' },
    { label: 'Khammam', value: 'khammam' },
    { label: 'Karimnagar', value: 'karimnagar' },
    { label: 'Ramagundam', value: 'ramagundam' },
    { label: 'Mahbubnagar', value: 'mahbubnagar' },
    { label: 'Nalgonda', value: 'nalgonda' },
    { label: 'Adilabad', value: 'adilabad' },
    { label: 'Suryapet', value: 'suryapet' },
    { label: 'Miryalaguda', value: 'miryalaguda' },
    { label: 'Siddipet', value: 'siddipet' },
    { label: 'Mancherial', value: 'mancherial' },
    { label: 'Kothagudem', value: 'kothagudem' },
    { label: 'Jagtial', value: 'jagtial' }
  ],
  TR: [
    { label: 'Agartala', value: 'agartala' },
    { label: 'Dharmanagar', value: 'dharmanagar' },
    { label: 'Udaipur', value: 'udaipur_tr' },
    { label: 'Kailasahar', value: 'kailasahar' },
    { label: 'Ambassa', value: 'ambassa' },
    { label: 'Belonia', value: 'belonia' },
    { label: 'Khowai', value: 'khowai' }
  ],
  UP: [
    { label: 'Lucknow', value: 'lucknow' }, 
    { label: 'Kanpur', value: 'kanpur' }, 
    { label: 'Noida', value: 'noida' }, 
    { label: 'Varanasi', value: 'varanasi' },
    { label: 'Ghaziabad', value: 'ghaziabad' },
    { label: 'Agra', value: 'agra' },
    { label: 'Meerut', value: 'meerut' },
    { label: 'Prayagraj (Allahabad)', value: 'prayagraj' },
    { label: 'Bareilly', value: 'bareilly' },
    { label: 'Aligarh', value: 'aligarh' },
    { label: 'Moradabad', value: 'moradabad' },
    { label: 'Saharanpur', value: 'saharanpur' },
    { label: 'Gorakhpur', value: 'gorakhpur' },
    { label: 'Ayodhya', value: 'ayodhya' },
    { label: 'Jhansi', value: 'jhansi' },
    { label: 'Muzaffarnagar', value: 'muzaffarnagar' },
    { label: 'Mathura', value: 'mathura' },
    { label: 'Firozabad', value: 'firozabad' },
    { label: 'Greater Noida', value: 'greater_noida' },
    { label: 'Lakhimpur', value: 'lakhimpur' },
    { label: 'Shahjahanpur', value: 'shahjahanpur' },
    { label: 'Farrukhabad', value: 'farrukhabad' },
    { label: 'Mau', value: 'mau' },
    { label: 'Hapur', value: 'hapur' }
  ],
  UK: [
    { label: 'Dehradun', value: 'dehradun' }, 
    { label: 'Haridwar', value: 'haridwar' },
    { label: 'Haldwani', value: 'haldwani' },
    { label: 'Rudrapur', value: 'rudrapur' },
    { label: 'Roorkee', value: 'roorkee' },
    { label: 'Kashipur', value: 'kashipur' },
    { label: 'Rishikesh', value: 'rishikesh' },
    { label: 'Nainital', value: 'nainital' },
    { label: 'Pithoragarh', value: 'pithoragarh' },
    { label: 'Almora', value: 'almora' }
  ],
  WB: [
    { label: 'Kolkata', value: 'kolkata' }, 
    { label: 'Howrah', value: 'howrah' }, 
    { label: 'Siliguri', value: 'siliguri' },
    { label: 'Asansol', value: 'asansol' },
    { label: 'Durgapur', value: 'durgapur' },
    { label: 'Bardhaman', value: 'bardhaman' },
    { label: 'Malda', value: 'malda' },
    { label: 'Baharampur', value: 'baharampur' },
    { label: 'Kharagpur', value: 'kharagpur' },
    { label: 'Haldia', value: 'haldia' },
    { label: 'Jalpaiguri', value: 'jalpaiguri' },
    { label: 'Darjeeling', value: 'darjeeling' },
    { label: 'Kalyani', value: 'kalyani' },
    { label: 'Habra', value: 'habra' },
    { label: 'Ranaghat', value: 'ranaghat' }
  ],
  AN: [
    { label: 'Port Blair', value: 'port_blair' },
    { label: 'Garacharma', value: 'garacharma' },
    { label: 'Bambooflat', value: 'bambooflat' },
    { label: 'Prothrapur', value: 'prothrapur' }
  ],
  CH: [
    { label: 'Chandigarh', value: 'chandigarh' }
  ],
  DN: [
    { label: 'Silvassa', value: 'silvassa' },
    { label: 'Dadra', value: 'dadra' }
  ],
  DD: [
    { label: 'Daman', value: 'daman' },
    { label: 'Diu', value: 'diu' }
  ],
  DL: [
    { label: 'New Delhi', value: 'new_delhi' }, 
    { label: 'North Delhi', value: 'north_delhi' }, 
    { label: 'South Delhi', value: 'south_delhi' },
    { label: 'East Delhi', value: 'east_delhi' },
    { label: 'West Delhi', value: 'west_delhi' },
    { label: 'Dwarka', value: 'dwarka' },
    { label: 'Rohini', value: 'rohini' },
    { label: 'Karol Bagh', value: 'karol_bagh' },
    { label: 'Connaught Place', value: 'connaught_place' }
  ],
  JK: [
    { label: 'Srinagar', value: 'srinagar' }, 
    { label: 'Jammu', value: 'jammu' },
    { label: 'Anantnag', value: 'anantnag' },
    { label: 'Baramulla', value: 'baramulla' },
    { label: 'Kathua', value: 'kathua' },
    { label: 'Samba', value: 'samba' },
    { label: 'Udhampur', value: 'udhampur' },
    { label: 'Poonch', value: 'poonch' },
    { label: 'Kupwara', value: 'kupwara' }
  ],
  LA: [
    { label: 'Leh', value: 'leh' }, 
    { label: 'Kargil', value: 'kargil' }
  ],
  LD: [
    { label: 'Kavaratti', value: 'kavaratti' },
    { label: 'Agatti', value: 'agatti' },
    { label: 'Minicoy', value: 'minicoy' },
    { label: 'Amini', value: 'amini' }
  ],
  PY: [
    { label: 'Puducherry', value: 'puducherry' },
    { label: 'Karaikal', value: 'karaikal' },
    { label: 'Mahe', value: 'mahe' },
    { label: 'Yanam', value: 'yanam' }
  ],
  default: []
};

export const STUDY_ABROAD_COUNTRIES = [
  { label: 'USA', value: 'USA' },
  { label: 'United Kingdom', value: 'UK' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'France', value: 'France' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'Italy', value: 'IT' },
];

// Living expenses are fixed in Lakhs (INR) based on country standards
export const FIXED_LIVING_EXPENSES: Record<string, number> = {
  'USA': 12.0,
  'UK': 10.0,
  'Canada': 9.0,
  'Australia': 11.0,
  'Germany': 8.5,
  'France': 8.0,
  'Ireland': 9.5,
  'Singapore': 10.5,
  'NZ': 10.0,
  'NL': 9.0,
  'IT': 7.5,
};

export const COUNTRY_CODES = [
  { label: '+91 (IN) - India', value: '+91' },
  { label: '+1 (US) - United States', value: '+1' },
  { label: '+44 (UK) - United Kingdom', value: '+44' },
  { label: '+61 (AU) - Australia', value: '+61' },
  { label: '+1 (CA) - Canada', value: '+1-CA' }, // Value distinguished if needed by backend, otherwise '+1'
  { label: '+971 (UAE) - United Arab Emirates', value: '+971' },
  { label: '+64 (NZ) - New Zealand', value: '+64' },
  { label: '+65 (SG) - Singapore', value: '+65' },
  { label: '+49 (DE) - Germany', value: '+49' },
  { label: '+33 (FR) - France', value: '+33' },
  { label: '+353 (IE) - Ireland', value: '+353' },
  { label: '+31 (NL) - Netherlands', value: '+31' },
  { label: '+39 (IT) - Italy', value: '+39' },
  { label: '+34 (ES) - Spain', value: '+34' },
  { label: '+41 (CH) - Switzerland', value: '+41' },
  { label: '+46 (SE) - Sweden', value: '+46' },
  { label: '+47 (NO) - Norway', value: '+47' },
  { label: '+45 (DK) - Denmark', value: '+45' },
  { label: '+358 (FI) - Finland', value: '+358' },
  { label: '+32 (BE) - Belgium', value: '+32' },
  { label: '+43 (AT) - Austria', value: '+43' },
  { label: '+351 (PT) - Portugal', value: '+351' },
  { label: '+7 (RU) - Russia', value: '+7' },
  { label: '+86 (CN) - China', value: '+86' },
  { label: '+81 (JP) - Japan', value: '+81' },
  { label: '+82 (KR) - South Korea', value: '+82' },
  { label: '+852 (HK) - Hong Kong', value: '+852' },
  { label: '+886 (TW) - Taiwan', value: '+886' },
  { label: '+60 (MY) - Malaysia', value: '+60' },
  { label: '+66 (TH) - Thailand', value: '+66' },
  { label: '+62 (ID) - Indonesia', value: '+62' },
  { label: '+63 (PH) - Philippines', value: '+63' },
  { label: '+84 (VN) - Vietnam', value: '+84' },
  { label: '+966 (SA) - Saudi Arabia', value: '+966' },
  { label: '+965 (KW) - Kuwait', value: '+965' },
  { label: '+968 (OM) - Oman', value: '+968' },
  { label: '+974 (QA) - Qatar', value: '+974' },
  { label: '+973 (BH) - Bahrain', value: '+973' },
  { label: '+27 (ZA) - South Africa', value: '+27' },
  { label: '+20 (EG) - Egypt', value: '+20' },
  { label: '+234 (NG) - Nigeria', value: '+234' },
  { label: '+254 (KE) - Kenya', value: '+254' },
  { label: '+55 (BR) - Brazil', value: '+55' },
  { label: '+52 (MX) - Mexico', value: '+52' },
  { label: '+54 (AR) - Argentina', value: '+54' },
  { label: '+56 (CL) - Chile', value: '+56' },
  { label: '+57 (CO) - Colombia', value: '+57' },
  { label: '+94 (LK) - Sri Lanka', value: '+94' },
  { label: '+92 (PK) - Pakistan', value: '+92' },
  { label: '+880 (BD) - Bangladesh', value: '+880' },
  { label: '+977 (NP) - Nepal', value: '+977' },
  { label: '+960 (MV) - Maldives', value: '+960' },
  { label: '+380 (UA) - Ukraine', value: '+380' },
  { label: '+48 (PL) - Poland', value: '+48' },
  { label: '+420 (CZ) - Czech Republic', value: '+420' },
  { label: '+90 (TR) - Turkey', value: '+90' },
  { label: '+972 (IL) - Israel', value: '+972' },
  { label: '+98 (IR) - Iran', value: '+98' },
  { label: '+964 (IQ) - Iraq', value: '+964' },
  { label: '+30 (GR) - Greece', value: '+30' },
  { label: '+36 (HU) - Hungary', value: '+36' },
  { label: '+40 (RO) - Romania', value: '+40' },
  { label: '+352 (LU) - Luxembourg', value: '+352' },
  { label: '+356 (MT) - Malta', value: '+356' },
  { label: '+357 (CY) - Cyprus', value: '+357' },
  { label: '+381 (RS) - Serbia', value: '+381' },
  { label: '+385 (HR) - Croatia', value: '+385' },
  { label: '+359 (BG) - Bulgaria', value: '+359' },
  { label: '+370 (LT) - Lithuania', value: '+370' },
  { label: '+371 (LV) - Latvia', value: '+371' },
  { label: '+372 (EE) - Estonia', value: '+372' },
  { label: '+421 (SK) - Slovakia', value: '+421' },
  { label: '+386 (SI) - Slovenia', value: '+386' },
  { label: '+354 (IS) - Iceland', value: '+354' },
  { label: '+212 (MA) - Morocco', value: '+212' },
  { label: '+216 (TN) - Tunisia', value: '+216' },
  { label: '+213 (DZ) - Algeria', value: '+213' },
  { label: '+211 (SS) - South Sudan', value: '+211' },
  { label: '+249 (SD) - Sudan', value: '+249' },
  { label: '+251 (ET) - Ethiopia', value: '+251' },
  { label: '+233 (GH) - Ghana', value: '+233' },
  { label: '+255 (TZ) - Tanzania', value: '+255' },
  { label: '+256 (UG) - Uganda', value: '+256' },
  { label: '+263 (ZW) - Zimbabwe', value: '+263' },
  { label: '+260 (ZM) - Zambia', value: '+260' },
  { label: '+244 (AO) - Angola', value: '+244' },
  { label: '+231 (LR) - Liberia', value: '+231' },
  { label: '+218 (LY) - Libya', value: '+218' },
  { label: '+264 (NA) - Namibia', value: '+264' },
  { label: '+267 (BW) - Botswana', value: '+267' },
  { label: '+230 (MU) - Mauritius', value: '+230' },
  { label: '+248 (SC) - Seychelles', value: '+248' },
  { label: '+51 (PE) - Peru', value: '+51' },
  { label: '+58 (VE) - Venezuela', value: '+58' },
  { label: '+593 (EC) - Ecuador', value: '+593' },
  { label: '+595 (PY) - Paraguay', value: '+595' },
  { label: '+598 (UY) - Uruguay', value: '+598' },
  { label: '+591 (BO) - Bolivia', value: '+591' },
  { label: '+506 (CR) - Costa Rica', value: '+506' },
  { label: '+507 (PA) - Panama', value: '+507' },
  { label: '+502 (GT) - Guatemala', value: '+502' },
  { label: '+503 (SV) - El Salvador', value: '+503' },
  { label: '+504 (HN) - Honduras', value: '+504' },
  { label: '+505 (NI) - Nicaragua', value: '+505' },
  { label: '+53 (CU) - Cuba', value: '+53' },
  { label: '+1-809 (DO) - Dominican Republic', value: '+1-809' },
  { label: '+509 (HT) - Haiti', value: '+509' },
  { label: '+1-242 (BS) - Bahamas', value: '+1-242' },
  { label: '+1-246 (BB) - Barbados', value: '+1-246' },
  { label: '+1-876 (JM) - Jamaica', value: '+1-876' },
  { label: '+1-868 (TT) - Trinidad & Tobago', value: '+1-868' },
  { label: '+679 (FJ) - Fiji', value: '+679' },
  { label: '+6PNG (PG) - Papua New Guinea', value: '+675' },
  { label: '+93 (AF) - Afghanistan', value: '+93' },
  { label: '+994 (AZ) - Azerbaijan', value: '+994' },
  { label: '+995 (GE) - Georgia', value: '+995' },
  { label: '+374 (AM) - Armenia', value: '+374' },
  { label: '+976 (MN) - Mongolia', value: '+976' },
  { label: '+992 (TJ) - Tajikistan', value: '+992' },
  { label: '+993 (TM) - Turkmenistan', value: '+993' },
  { label: '+996 (KG) - Kyrgyzstan', value: '+996' },
  { label: '+998 (UZ) - Uzbekistan', value: '+998' },
  { label: '+7-K (KZ) - Kazakhstan', value: '+7-7' },
  { label: '+95 (MM) - Myanmar', value: '+95' },
  { label: '+855 (KH) - Cambodia', value: '+855' },
  { label: '+856 (LA) - Laos', value: '+856' },
  { label: '+967 (YE) - Yemen', value: '+967' },
  { label: '+962 (JO) - Jordan', value: '+962' },
  { label: '+961 (LB) - Lebanon', value: '+961' },
  { label: '+963 (SY) - Syria', value: '+963' },
  { label: '+970 (PS) - Palestine', value: '+970' },
  { label: '+376 (AD) - Andorra', value: '+376' },
  { label: '+377 (MC) - Monaco', value: '+377' },
  { label: '+378 (SM) - San Marino', value: '+378' },
  { label: '+379 (VA) - Vatican City', value: '+379' },
  { label: '+423 (LI) - Liechtenstein', value: '+423' }
];